apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    app: todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: markhaur/todo:latest
        ports:
        - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo
  name: todo
spec:
  selector:
    app: todo
  ports:
  - name: default
    protocol: TCP
    port: 80
    targetPort: 8085
