version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=todo
    networks:
      - todonetwork
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16687:16686"
    networks:
      - todonetwork
  todo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - TODOAPP_CONFIG_PATH=docker.env
    depends_on:
      - postgres
    networks:
      - todonetwork
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]

networks:
  todonetwork:
    name: todo_network
      #    driver: default 
